In [1]:
!cat olympics.csv

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Denmark (DEN) [Z],26,43,68,68,179,13,0,1,0,1,39,43,69,68,180
Djibouti (DJI) [B],7,0,0,1,1,0,0,0,0,0,7,0,0,1,1
Dominican Republic (DOM),13,3,2,1,6,0,0,0,0,0,13,3,2,1,6
Ecuador (ECU),13,1,1,0,2,0,0,0,0,0,13,1,1,0,2
Egypt (EGY) [EGY] [Z],21,7,9,10,26,1,0,0,0,0,22,7,9,10,26
Eritrea (ERI),4,0,0,1,1,0,0,0,0,0,4,0,0,1,1
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Ethiopia (ETH),12,21,7,17,45,2,0,0,0,0,14,21,7,17,45
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
France (FRA) [O] [P] [Z],27,202,223,246,671,22,31,31,47,109,49,233,254,293,780
Gabon (GAB),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Georgia (GEO),5,6,5,14,25,6,0,0,0,0,11,6,5,14,25
Germany (GER) [GER] [Z],15,174,182,217,573,11,78,78,53,209,26,252,260,270,782
United Team of Germany (EUA) [EUA],3,28,54,36,118,3,8,6,5,19,6,36,60,41,137
East Germany (GDR) [GDR],5,153,129,127,409,6,39,36,35,110,11,192,165,162,519
West Germany (FRG) [FRG],5,56,67,81,204,6,11,15,13,39,11,67,82,94,243
Ghana (GHA) [GHA],13,0,1,3,4,1,0,0,0,0,14,0,1,3,4
Great Britain (GBR) [GBR] [Z],27,236,272,272,780,22,10,4,12,26,49,246,276,284,806
Greece (GRE) [Z],27,30,42,39,111,18,0,0,0,0,45,30,42,39,111
Grenada (GRN),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
Guatemala (GUA),13,0,1,0,1,1,0,0,0,0,14,0,1,0,1
Guyana (GUY) [GUY],16,0,0,1,1,0,0,0,0,0,16,0,0,1,1
Haiti (HAI) [J],14,0,1,1,2,0,0,0,0,0,14,0,1,1,2
Hong Kong (HKG) [HKG],15,1,1,1,3,4,0,0,0,0,19,1,1,1,3
Hungary (HUN),25,167,144,165,476,22,0,2,4,6,47,167,146,169,482
Iceland (ISL),19,0,2,2,4,17,0,0,0,0,36,0,2,2,4
India (IND) [F],23,9,6,11,26,9,0,0,0,0,32,9,6,11,26
Indonesia (INA),14,6,10,11,27,0,0,0,0,0,14,6,10,11,27
Iran (IRI) [K],15,15,20,25,60,10,0,0,0,0,25,15,20,25,60
Iraq (IRQ),13,0,0,1,1,0,0,0,0,0,13,0,0,1,1
Ireland (IRL),20,9,8,12,29,6,0,0,0,0,26,9,8,12,29
Israel (ISR),15,1,1,5,7,6,0,0,0,0,21,1,1,5,7
Italy (ITA) [M] [S],26,198,166,185,549,22,37,34,43,114,48,235,200,228,663
Jamaica (JAM) [JAM],16,17,30,20,67,7,0,0,0,0,23,17,30,20,67
Japan (JPN),21,130,126,142,398,20,10,17,18,45,41,140,143,160,443
Kazakhstan (KAZ),5,16,17,19,52,6,1,3,3,7,11,17,20,22,59
Kenya (KEN),13,25,32,29,86,3,0,0,0,0,16,25,32,29,86
North Korea (PRK),9,14,12,21,47,8,0,1,1,2,17,14,13,22,49
South Korea (KOR),16,81,82,80,243,17,26,17,10,53,33,107,99,90,296
Kuwait (KUW),12,0,0,2,2,0,0,0,0,0,12,0,0,2,2
Kyrgyzstan (KGZ),5,0,1,2,3,6,0,0,0,0,11,0,1,2,3
Latvia (LAT),10,3,11,5,19,10,0,4,3,7,20,3,15,8,26
Lebanon (LIB),16,0,2,2,4,16,0,0,0,0,32,0,2,2,4
Liechtenstein (LIE),16,0,0,0,0,18,2,2,5,9,34,2,2,5,9
Lithuania (LTU),8,6,5,10,21,8,0,0,0,0,16,6,5,10,21
Luxembourg (LUX) [O],22,1,1,0,2,8,0,2,0,2,30,1,3,0,4
Macedonia (MKD),5,0,0,1,1,5,0,0,0,0,10,0,0,1,1
Malaysia (MAS) [MAS],12,0,3,3,6,0,0,0,0,0,12,0,3,3,6
Mauritius (MRI),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Mexico (MEX),22,13,21,28,62,8,0,0,0,0,30,13,21,28,62
Moldova (MDA),5,0,2,5,7,6,0,0,0,0,11,0,2,5,7
Mongolia (MGL),12,2,9,13,24,13,0,0,0,0,25,2,9,13,24
Montenegro (MNE),2,0,1,0,1,2,0,0,0,0,4,0,1,0,1
Morocco (MAR),13,6,5,11,22,6,0,0,0,0,19,6,5,11,22
Mozambique (MOZ),9,1,0,1,2,0,0,0,0,0,9,1,0,1,2
Namibia (NAM),6,0,4,0,4,0,0,0,0,0,6,0,4,0,4
Netherlands (NED) [Z],25,77,85,104,266,20,37,38,35,110,45,114,123,139,376
Netherlands Antilles (AHO) [AHO] [I],13,0,1,0,1,2,0,0,0,0,15,0,1,0,1
New Zealand (NZL) [NZL],22,42,18,39,99,15,0,1,0,1,37,42,19,39,100
Niger (NIG),11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Nigeria (NGR),15,3,8,12,23,0,0,0,0,0,15,3,8,12,23
Norway (NOR) [Q],24,56,49,43,148,22,118,111,100,329,46,174,160,143,477
Pakistan (PAK),16,3,3,4,10,2,0,0,0,0,18,3,3,4,10
Panama (PAN),16,1,0,2,3,0,0,0,0,0,16,1,0,2,3
Paraguay (PAR),11,0,1,0,1,1,0,0,0,0,12,0,1,0,1
Peru (PER) [L],17,1,3,0,4,2,0,0,0,0,19,1,3,0,4
Philippines (PHI),20,0,2,7,9,4,0,0,0,0,24,0,2,7,9
Poland (POL),20,64,82,125,271,22,6,7,7,20,42,70,89,132,291
Portugal (POR),23,4,8,11,23,7,0,0,0,0,30,4,8,11,23
Puerto Rico (PUR),17,0,2,6,8,6,0,0,0,0,23,0,2,6,8
Qatar (QAT),8,0,0,4,4,0,0,0,0,0,8,0,0,4,4
Romania (ROU),20,88,94,119,301,20,0,0,1,1,40,88,94,120,302
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Russian Empire (RU1) [RU1],3,1,4,3,8,0,0,0,0,0,3,1,4,3,8
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Saudi Arabia (KSA),10,0,1,2,3,0,0,0,0,0,10,0,1,2,3
Senegal (SEN),13,0,1,0,1,5,0,0,0,0,18,0,1,0,1
Serbia (SRB) [SRB],3,1,2,4,7,2,0,0,0,0,5,1,2,4,7
Serbia and Montenegro (SCG) [SCG],3,2,4,3,9,3,0,0,0,0,6,2,4,3,9
Singapore (SIN),15,0,2,2,4,0,0,0,0,0,15,0,2,2,4
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
South Africa (RSA),18,23,26,27,76,6,0,0,0,0,24,23,26,27,76
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [3]:
import pandas as pd 
df=pd.read_csv("olympics.csv")
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
6,Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
7,Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
8,Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
9,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
10,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
11,Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
12,Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
13,Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
14,Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
15,Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
16,Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
17,Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
18,British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
19,Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
20,Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
21,Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
22,Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
23,Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
24,China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
25,Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
26,Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
27,Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
28,Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
29,Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
119,Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
120,Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
121,Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
122,Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
123,Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
124,Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
125,Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
126,Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
127,Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
128,Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
129,Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
130,Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
131,Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
132,Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
133,Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
134,Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
135,United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
136,United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
137,Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
138,Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
139,Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
140,Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
141,Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
142,Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
143,Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
144,Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
145,Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
146,Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
147,Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [4]:
df=pd.read_csv("olympics.csv",index_col=0,skiprows=1)

In [5]:
df

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [6]:
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [7]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [9]:
df['Combined total'] >10

Afghanistan (AFG)                               False
Algeria (ALG)                                    True
Argentina (ARG)                                  True
Armenia (ARM)                                    True
Australasia (ANZ) [ANZ]                          True
Australia (AUS) [AUS] [Z]                        True
Austria (AUT)                                    True
Azerbaijan (AZE)                                 True
Bahamas (BAH)                                    True
Bahrain (BRN)                                   False
Barbados (BAR) [BAR]                            False
Belarus (BLR)                                    True
Belgium (BEL)                                    True
Bermuda (BER)                                   False
Bohemia (BOH) [BOH] [Z]                         False
Botswana (BOT)                                  False
Brazil (BRA)                                     True
British West Indies (BWI) [BWI]                 False
Bulgaria (BUL) [H]                               True
Burundi (BDI)                                   False
Cameroon (CMR)                                  False
Canada (CAN)                                     True
Chile (CHI) [I]                                  True
China (CHN) [CHN]                                True
Colombia (COL)                                   True
Costa Rica (CRC)                                False
Ivory Coast (CIV) [CIV]                         False
Croatia (CRO)                                    True
Cuba (CUB) [Z]                                   True
Cyprus (CYP)                                    False
                                                ...
Sri Lanka (SRI) [SRI]                           False
Sudan (SUD)                                     False
Suriname (SUR) [E]                              False
Sweden (SWE) [Z]                                 True
Switzerland (SUI)                                True
Syria (SYR)                                     False
Chinese Taipei (TPE) [TPE] [TPE2]                True
Tajikistan (TJK)                                False
Tanzania (TAN) [TAN]                            False
Thailand (THA)                                   True
Togo (TOG)                                      False
Tonga (TGA)                                     False
Trinidad and Tobago (TRI) [TRI]                  True
Tunisia (TUN)                                   False
Turkey (TUR)                                     True
Uganda (UGA)                                    False
Ukraine (UKR)                                    True
United Arab Emirates (UAE)                      False
United States (USA) [P] [Q] [R] [Z]              True
Uruguay (URU)                                   False
Uzbekistan (UZB)                                 True
Venezuela (VEN)                                  True
Vietnam (VIE)                                   False
Virgin Islands (ISV)                            False
Yugoslavia (YUG) [YUG]                           True
Independent Olympic Participants (IOP) [IOP]    False
Zambia (ZAM) [ZAM]                              False
Zimbabwe (ZIM) [ZIM]                            False
Mixed team (ZZX) [ZZX]                           True
Totals                                           True
Name: Combined total, dtype: bool

In [10]:
combined_10=df.where(df['Combined total']>10).copy()
combined_10

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0
Austria (AUT),26.0,18.0,33.0,35.0,86.0,22.0,59.0,78.0,81.0,218.0,48.0,77.0,111.0,116.0,304.0
Azerbaijan (AZE),5.0,6.0,5.0,15.0,26.0,5.0,0.0,0.0,0.0,0.0,10.0,6.0,5.0,15.0,26.0
Bahamas (BAH),15.0,5.0,2.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,5.0,12.0
Bahrain (BRN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barbados (BAR) [BAR],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belarus (BLR),5.0,12.0,24.0,39.0,75.0,6.0,6.0,4.0,5.0,15.0,11.0,18.0,28.0,44.0,90.0
Belgium (BEL),25.0,37.0,52.0,53.0,142.0,20.0,1.0,1.0,3.0,5.0,45.0,38.0,53.0,56.0,147.0
Bermuda (BER),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bohemia (BOH) [BOH] [Z],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Botswana (BOT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brazil (BRA),21.0,23.0,30.0,55.0,108.0,7.0,0.0,0.0,0.0,0.0,28.0,23.0,30.0,55.0,108.0
British West Indies (BWI) [BWI],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bulgaria (BUL) [H],19.0,51.0,85.0,78.0,214.0,19.0,1.0,2.0,3.0,6.0,38.0,52.0,87.0,81.0,220.0
Burundi (BDI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cameroon (CMR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada (CAN),25.0,59.0,99.0,121.0,279.0,22.0,62.0,56.0,52.0,170.0,47.0,121.0,155.0,173.0,449.0
Chile (CHI) [I],22.0,2.0,7.0,4.0,13.0,16.0,0.0,0.0,0.0,0.0,38.0,2.0,7.0,4.0,13.0
China (CHN) [CHN],9.0,201.0,146.0,126.0,473.0,10.0,12.0,22.0,19.0,53.0,19.0,213.0,168.0,145.0,526.0
Colombia (COL),18.0,2.0,6.0,11.0,19.0,1.0,0.0,0.0,0.0,0.0,19.0,2.0,6.0,11.0,19.0
Costa Rica (CRC),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ivory Coast (CIV) [CIV],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Croatia (CRO),6.0,6.0,7.0,10.0,23.0,7.0,4.0,6.0,1.0,11.0,13.0,10.0,13.0,11.0,34.0
Cuba (CUB) [Z],19.0,72.0,67.0,70.0,209.0,0.0,0.0,0.0,0.0,0.0,19.0,72.0,67.0,70.0,209.0
Cyprus (CYP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sudan (SUD),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suriname (SUR) [E],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sweden (SWE) [Z],26.0,143.0,164.0,176.0,483.0,22.0,50.0,40.0,54.0,144.0,48.0,193.0,204.0,230.0,627.0
Switzerland (SUI),27.0,47.0,73.0,65.0,185.0,22.0,50.0,40.0,48.0,138.0,49.0,97.0,113.0,113.0,323.0
Syria (SYR),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chinese Taipei (TPE) [TPE] [TPE2],13.0,2.0,7.0,12.0,21.0,11.0,0.0,0.0,0.0,0.0,24.0,2.0,7.0,12.0,21.0
Tajikistan (TJK),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tanzania (TAN) [TAN],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Thailand (THA),15.0,7.0,6.0,11.0,24.0,3.0,0.0,0.0,0.0,0.0,18.0,7.0,6.0,11.0,24.0
Togo (TOG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tonga (TGA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trinidad and Tobago (TRI) [TRI],16.0,2.0,5.0,11.0,18.0,3.0,0.0,0.0,0.0,0.0,19.0,2.0,5.0,11.0,18.0
Tunisia (TUN),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turkey (TUR),21.0,39.0,25.0,24.0,88.0,16.0,0.0,0.0,0.0,0.0,37.0,39.0,25.0,24.0,88.0
Uganda (UGA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ukraine (UKR),5.0,33.0,27.0,55.0,115.0,6.0,2.0,1.0,4.0,7.0,11.0,35.0,28.0,59.0,122.0
United Arab Emirates (UAE),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States (USA) [P] [Q] [R] [Z],26.0,976.0,757.0,666.0,2399.0,22.0,96.0,102.0,84.0,282.0,48.0,1072.0,859.0,750.0,2681.0
Uruguay (URU),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Uzbekistan (UZB),5.0,5.0,5.0,10.0,20.0,6.0,1.0,0.0,0.0,1.0,11.0,6.0,5.0,10.0,21.0
Venezuela (VEN),17.0,2.0,2.0,8.0,12.0,4.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,8.0,12.0
Vietnam (VIE),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Virgin Islands (ISV),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yugoslavia (YUG) [YUG],16.0,26.0,29.0,28.0,83.0,14.0,0.0,3.0,1.0,4.0,30.0,26.0,32.0,29.0,87.0
Independent Olympic Participants (IOP) [IOP],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia (ZAM) [ZAM],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe (ZIM) [ZIM],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mixed team (ZZX) [ZZX],3.0,8.0,5.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,4.0,17.0
Totals,27.0,4809.0,4775.0,5130.0,14714.0,22.0,959.0,958.0,948.0,2865.0,49.0,5768.0,5733.0,6078.0,17579.0

In [11]:
only_gold=df.where(df['Gold']>0)
only_gold.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0

In [12]:
only_gold['Gold'].count()

100

In [13]:
df['Gold'].count()

147

In [14]:
only_gold=only_gold.dropna()
only_gold

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12.0,5.0,2.0,8.0,15.0,3.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,8.0,15.0
Argentina (ARG),23.0,18.0,24.0,28.0,70.0,18.0,0.0,0.0,0.0,0.0,41.0,18.0,24.0,28.0,70.0
Armenia (ARM),5.0,1.0,2.0,9.0,12.0,6.0,0.0,0.0,0.0,0.0,11.0,1.0,2.0,9.0,12.0
Australasia (ANZ) [ANZ],2.0,3.0,4.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,5.0,12.0
Australia (AUS) [AUS] [Z],25.0,139.0,152.0,177.0,468.0,18.0,5.0,3.0,4.0,12.0,43.0,144.0,155.0,181.0,480.0
Austria (AUT),26.0,18.0,33.0,35.0,86.0,22.0,59.0,78.0,81.0,218.0,48.0,77.0,111.0,116.0,304.0
Azerbaijan (AZE),5.0,6.0,5.0,15.0,26.0,5.0,0.0,0.0,0.0,0.0,10.0,6.0,5.0,15.0,26.0
Bahamas (BAH),15.0,5.0,2.0,5.0,12.0,0.0,0.0,0.0,0.0,0.0,15.0,5.0,2.0,5.0,12.0
Belarus (BLR),5.0,12.0,24.0,39.0,75.0,6.0,6.0,4.0,5.0,15.0,11.0,18.0,28.0,44.0,90.0
Belgium (BEL),25.0,37.0,52.0,53.0,142.0,20.0,1.0,1.0,3.0,5.0,45.0,38.0,53.0,56.0,147.0
Brazil (BRA),21.0,23.0,30.0,55.0,108.0,7.0,0.0,0.0,0.0,0.0,28.0,23.0,30.0,55.0,108.0
Bulgaria (BUL) [H],19.0,51.0,85.0,78.0,214.0,19.0,1.0,2.0,3.0,6.0,38.0,52.0,87.0,81.0,220.0
Burundi (BDI),5.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,1.0
Cameroon (CMR),13.0,3.0,1.0,1.0,5.0,1.0,0.0,0.0,0.0,0.0,14.0,3.0,1.0,1.0,5.0
Canada (CAN),25.0,59.0,99.0,121.0,279.0,22.0,62.0,56.0,52.0,170.0,47.0,121.0,155.0,173.0,449.0
Chile (CHI) [I],22.0,2.0,7.0,4.0,13.0,16.0,0.0,0.0,0.0,0.0,38.0,2.0,7.0,4.0,13.0
China (CHN) [CHN],9.0,201.0,146.0,126.0,473.0,10.0,12.0,22.0,19.0,53.0,19.0,213.0,168.0,145.0,526.0
Colombia (COL),18.0,2.0,6.0,11.0,19.0,1.0,0.0,0.0,0.0,0.0,19.0,2.0,6.0,11.0,19.0
Costa Rica (CRC),14.0,1.0,1.0,2.0,4.0,6.0,0.0,0.0,0.0,0.0,20.0,1.0,1.0,2.0,4.0
Croatia (CRO),6.0,6.0,7.0,10.0,23.0,7.0,4.0,6.0,1.0,11.0,13.0,10.0,13.0,11.0,34.0
Cuba (CUB) [Z],19.0,72.0,67.0,70.0,209.0,0.0,0.0,0.0,0.0,0.0,19.0,72.0,67.0,70.0,209.0
Czech Republic (CZE) [CZE],5.0,14.0,15.0,15.0,44.0,6.0,7.0,9.0,8.0,24.0,11.0,21.0,24.0,23.0,68.0
Czechoslovakia (TCH) [TCH],16.0,49.0,49.0,45.0,143.0,16.0,2.0,8.0,15.0,25.0,32.0,51.0,57.0,60.0,168.0
Denmark (DEN) [Z],26.0,43.0,68.0,68.0,179.0,13.0,0.0,1.0,0.0,1.0,39.0,43.0,69.0,68.0,180.0
Dominican Republic (DOM),13.0,3.0,2.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,13.0,3.0,2.0,1.0,6.0
Ecuador (ECU),13.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,13.0,1.0,1.0,0.0,2.0
Egypt (EGY) [EGY] [Z],21.0,7.0,9.0,10.0,26.0,1.0,0.0,0.0,0.0,0.0,22.0,7.0,9.0,10.0,26.0
Estonia (EST),11.0,9.0,9.0,15.0,33.0,9.0,4.0,2.0,1.0,7.0,20.0,13.0,11.0,16.0,40.0
Ethiopia (ETH),12.0,21.0,7.0,17.0,45.0,2.0,0.0,0.0,0.0,0.0,14.0,21.0,7.0,17.0,45.0
Finland (FIN),24.0,101.0,84.0,117.0,302.0,22.0,42.0,62.0,57.0,161.0,46.0,143.0,146.0,174.0,463.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Russia (RUS) [RUS],5.0,132.0,121.0,142.0,395.0,6.0,49.0,40.0,35.0,124.0,11.0,181.0,161.0,177.0,519.0
Russian Empire (RU1) [RU1],3.0,1.0,4.0,3.0,8.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,3.0,8.0
Soviet Union (URS) [URS],9.0,395.0,319.0,296.0,1010.0,9.0,78.0,57.0,59.0,194.0,18.0,473.0,376.0,355.0,1204.0
Unified Team (EUN) [EUN],1.0,45.0,38.0,29.0,112.0,1.0,9.0,6.0,8.0,23.0,2.0,54.0,44.0,37.0,135.0
Serbia (SRB) [SRB],3.0,1.0,2.0,4.0,7.0,2.0,0.0,0.0,0.0,0.0,5.0,1.0,2.0,4.0,7.0
Serbia and Montenegro (SCG) [SCG],3.0,2.0,4.0,3.0,9.0,3.0,0.0,0.0,0.0,0.0,6.0,2.0,4.0,3.0,9.0
Slovakia (SVK) [SVK],5.0,7.0,9.0,8.0,24.0,6.0,2.0,2.0,1.0,5.0,11.0,9.0,11.0,9.0,29.0
Slovenia (SLO),6.0,4.0,6.0,9.0,19.0,7.0,2.0,4.0,9.0,15.0,13.0,6.0,10.0,18.0,34.0
South Africa (RSA),18.0,23.0,26.0,27.0,76.0,6.0,0.0,0.0,0.0,0.0,24.0,23.0,26.0,27.0,76.0
Spain (ESP) [Z],22.0,37.0,59.0,35.0,131.0,19.0,1.0,0.0,1.0,2.0,41.0,38.0,59.0,36.0,133.0
Suriname (SUR) [E],11.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,11.0,1.0,0.0,1.0,2.0
Sweden (SWE) [Z],26.0,143.0,164.0,176.0,483.0,22.0,50.0,40.0,54.0,144.0,48.0,193.0,204.0,230.0,627.0
Switzerland (SUI),27.0,47.0,73.0,65.0,185.0,22.0,50.0,40.0,48.0,138.0,49.0,97.0,113.0,113.0,323.0
Syria (SYR),12.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0,1.0,1.0,3.0
Chinese Taipei (TPE) [TPE] [TPE2],13.0,2.0,7.0,12.0,21.0,11.0,0.0,0.0,0.0,0.0,24.0,2.0,7.0,12.0,21.0
Thailand (THA),15.0,7.0,6.0,11.0,24.0,3.0,0.0,0.0,0.0,0.0,18.0,7.0,6.0,11.0,24.0
Trinidad and Tobago (TRI) [TRI],16.0,2.0,5.0,11.0,18.0,3.0,0.0,0.0,0.0,0.0,19.0,2.0,5.0,11.0,18.0
Tunisia (TUN),13.0,3.0,3.0,4.0,10.0,0.0,0.0,0.0,0.0,0.0,13.0,3.0,3.0,4.0,10.0
Turkey (TUR),21.0,39.0,25.0,24.0,88.0,16.0,0.0,0.0,0.0,0.0,37.0,39.0,25.0,24.0,88.0
Uganda (UGA),14.0,2.0,3.0,2.0,7.0,0.0,0.0,0.0,0.0,0.0,14.0,2.0,3.0,2.0,7.0
Ukraine (UKR),5.0,33.0,27.0,55.0,115.0,6.0,2.0,1.0,4.0,7.0,11.0,35.0,28.0,59.0,122.0
United Arab Emirates (UAE),8.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,0.0,1.0
United States (USA) [P] [Q] [R] [Z],26.0,976.0,757.0,666.0,2399.0,22.0,96.0,102.0,84.0,282.0,48.0,1072.0,859.0,750.0,2681.0
Uruguay (URU),20.0,2.0,2.0,6.0,10.0,1.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,6.0,10.0
Uzbekistan (UZB),5.0,5.0,5.0,10.0,20.0,6.0,1.0,0.0,0.0,1.0,11.0,6.0,5.0,10.0,21.0
Venezuela (VEN),17.0,2.0,2.0,8.0,12.0,4.0,0.0,0.0,0.0,0.0,21.0,2.0,2.0,8.0,12.0
Yugoslavia (YUG) [YUG],16.0,26.0,29.0,28.0,83.0,14.0,0.0,3.0,1.0,4.0,30.0,26.0,32.0,29.0,87.0
Zimbabwe (ZIM) [ZIM],12.0,3.0,4.0,1.0,8.0,1.0,0.0,0.0,0.0,0.0,13.0,3.0,4.0,1.0,8.0
Mixed team (ZZX) [ZZX],3.0,8.0,5.0,4.0,17.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,5.0,4.0,17.0
Totals,27.0,4809.0,4775.0,5130.0,14714.0,22.0,959.0,958.0,948.0,2865.0,49.0,5768.0,5733.0,6078.0,17579.0

In [15]:
only_gold['Gold'].count()

100

In [16]:
gold=df[df['Gold']>0]
gold

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Czech Republic (CZE) [CZE],5,14,15,15,44,6,7,9,8,24,11,21,24,23,68
Czechoslovakia (TCH) [TCH],16,49,49,45,143,16,2,8,15,25,32,51,57,60,168
Denmark (DEN) [Z],26,43,68,68,179,13,0,1,0,1,39,43,69,68,180
Dominican Republic (DOM),13,3,2,1,6,0,0,0,0,0,13,3,2,1,6
Ecuador (ECU),13,1,1,0,2,0,0,0,0,0,13,1,1,0,2
Egypt (EGY) [EGY] [Z],21,7,9,10,26,1,0,0,0,0,22,7,9,10,26
Estonia (EST),11,9,9,15,33,9,4,2,1,7,20,13,11,16,40
Ethiopia (ETH),12,21,7,17,45,2,0,0,0,0,14,21,7,17,45
Finland (FIN),24,101,84,117,302,22,42,62,57,161,46,143,146,174,463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519
Russian Empire (RU1) [RU1],3,1,4,3,8,0,0,0,0,0,3,1,4,3,8
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Unified Team (EUN) [EUN],1,45,38,29,112,1,9,6,8,23,2,54,44,37,135
Serbia (SRB) [SRB],3,1,2,4,7,2,0,0,0,0,5,1,2,4,7
Serbia and Montenegro (SCG) [SCG],3,2,4,3,9,3,0,0,0,0,6,2,4,3,9
Slovakia (SVK) [SVK],5,7,9,8,24,6,2,2,1,5,11,9,11,9,29
Slovenia (SLO),6,4,6,9,19,7,2,4,9,15,13,6,10,18,34
South Africa (RSA),18,23,26,27,76,6,0,0,0,0,24,23,26,27,76
Spain (ESP) [Z],22,37,59,35,131,19,1,0,1,2,41,38,59,36,133
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [21]:
len(df[(df['Gold'] >0) | (df['Gold.1'] >0)])

101

In [23]:
df[(df['Gold.1']>0) & (df['Gold']==0)]

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Liechtenstein (LIE),16,0,0,0,0,18,2,2,5,9,34,2,2,5,9

In [24]:
df['country']=df.index

In [25]:
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,country
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,Australia (AUS) [AUS] [Z]
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,Austria (AUT)
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26,Azerbaijan (AZE)
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12,Bahamas (BAH)
Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,Bahrain (BRN)
Barbados (BAR) [BAR],11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,Barbados (BAR) [BAR]
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,Belarus (BLR)
Belgium (BEL),25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,Belgium (BEL)
Bermuda (BER),17,0,0,1,1,7,0,0,0,0,24,0,0,1,1,Bermuda (BER)
Bohemia (BOH) [BOH] [Z],3,0,1,3,4,0,0,0,0,0,3,0,1,3,4,Bohemia (BOH) [BOH] [Z]
Botswana (BOT),9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,Botswana (BOT)
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108,Brazil (BRA)
British West Indies (BWI) [BWI],1,0,0,2,2,0,0,0,0,0,1,0,0,2,2,British West Indies (BWI) [BWI]
Bulgaria (BUL) [H],19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,Bulgaria (BUL) [H]
Burundi (BDI),5,1,0,0,1,0,0,0,0,0,5,1,0,0,1,Burundi (BDI)
Cameroon (CMR),13,3,1,1,5,1,0,0,0,0,14,3,1,1,5,Cameroon (CMR)
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,Canada (CAN)
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13,Chile (CHI) [I]
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,China (CHN) [CHN]
Colombia (COL),18,2,6,11,19,1,0,0,0,0,19,2,6,11,19,Colombia (COL)
Costa Rica (CRC),14,1,1,2,4,6,0,0,0,0,20,1,1,2,4,Costa Rica (CRC)
Ivory Coast (CIV) [CIV],12,0,1,0,1,0,0,0,0,0,12,0,1,0,1,Ivory Coast (CIV) [CIV]
Croatia (CRO),6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,Croatia (CRO)
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209,Cuba (CUB) [Z]
Cyprus (CYP),9,0,1,0,1,10,0,0,0,0,19,0,1,0,1,Cyprus (CYP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,Sri Lanka (SRI) [SRI]
Sudan (SUD),11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,Sudan (SUD)
Suriname (SUR) [E],11,1,0,1,2,0,0,0,0,0,11,1,0,1,2,Suriname (SUR) [E]
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,Sweden (SWE) [Z]
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,Switzerland (SUI)
Syria (SYR),12,1,1,1,3,0,0,0,0,0,12,1,1,1,3,Syria (SYR)
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21,Chinese Taipei (TPE) [TPE] [TPE2]
Tajikistan (TJK),5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,Tajikistan (TJK)
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,Tanzania (TAN) [TAN]
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24,Thailand (THA)
Togo (TOG),9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,Togo (TOG)
Tonga (TGA),8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,Tonga (TGA)
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18,Trinidad and Tobago (TRI) [TRI]
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10,Tunisia (TUN)
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88,Turkey (TUR)
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7,Uganda (UGA)
Ukraine (UKR),5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,Ukraine (UKR)
United Arab Emirates (UAE),8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,United Arab Emirates (UAE)
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,United States (USA) [P] [Q] [R] [Z]
Uruguay (URU),20,2,2,6,10,1,0,0,0,0,21,2,2,6,10,Uruguay (URU)
Uzbekistan (UZB),5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,Uzbekistan (UZB)
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12,Venezuela (VEN)
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2,Vietnam (VIE)
Virgin Islands (ISV),11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,Virgin Islands (ISV)
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,1,4,30,26,32,29,87,Yugoslavia (YUG) [YUG]
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,Independent Olympic Participants (IOP) [IOP]
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,Zambia (ZAM) [ZAM]
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8,Zimbabwe (ZIM) [ZIM]
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17,Mixed team (ZZX) [ZZX]
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579,Totals

In [26]:
df=df.set_index('Gold')
df.head()

,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,country
Gold,,,,,,,,,,,,,,,
0,13,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
5,12,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
18,23,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
1,5,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
3,2,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]

In [27]:
df=df.reset_index()
df.head()

,Gold,# Summer,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,country
0,0,13,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
1,5,12,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
2,18,23,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
3,1,5,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
4,3,2,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]

In [28]:
#multilevel index similar to composite keys

In [30]:
df=pd.read_csv("census.csv")
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [31]:
#get all unique values in a coloumn
df['SUMLEV'].unique()

array([40, 50])

In [33]:
#get all state names for the above census on the column STNAME
len(df['STNAME'].unique())

51

In [34]:
df=df[df['SUMLEV']==50]
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [35]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

,STNAME,CTYNAME,BIRTHS2010,BIRTHS2011,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,636,615,574,623,600,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,2187,2092,2160,2186,2240,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,335,300,283,260,269,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,266,245,259,247,253,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,744,710,646,618,603,57373,57711,57776,57734,57658,57673

In [36]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

                        BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME
Alabama Autauga County         151         636         615         574
        Baldwin County         517        2187        2092        2160
        Barbour County          70         335         300         283
        Bibb County             44         266         245         259
        Blount County          183         744         710         646

                        BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County         623         600            54660
        Baldwin County        2186        2240           183193
        Barbour County         260         269            27341
        Bibb County            247         253            22861
        Blount County          618         603            57373

                        POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME
Alabama Autauga County            55253            55175            55038
        Baldwin County           186659           190396           195126
        Barbour County            27226            27159            26973
        Bibb County               22733            22642            22512
        Blount County             57711            57776            57734

                        POPESTIMATE2014  POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County            55290            55347
        Baldwin County           199713           203709
        Barbour County            26815            26489
        Bibb County               22549            22583
        Blount County             57658            57673

In [40]:
df[:68]

                                BIRTHS2010  BIRTHS2011  BIRTHS2012  \
STNAME  CTYNAME
Alabama Autauga County                 151         636         615
        Baldwin County                 517        2187        2092
        Barbour County                  70         335         300
        Bibb County                     44         266         245
        Blount County                  183         744         710
        Bullock County                  39         169         122
        Butler County                   65         276         241
        Calhoun County                 317        1382        1357
        Chambers County                 81         401         393
        Cherokee County                 55         221         245
        Chilton County                 124         565         565
        Choctaw County                  29         114         110
        Clarke County                   49         259         292
        Clay County                     27         153         147
        Cleburne County                 41         184         183
        Coffee County                  168         677         622
        Colbert County                 162         605         623
        Conecuh County                  34         158         144
        Coosa County                    21          95         107
        Covington County               102         463         412
        Crenshaw County                 37         166         149
        Cullman County                 249         996         926
        Dale County                    173         692         705
        Dallas County                  130         583         585
        DeKalb County                  232         903         869
        Elmore County                  235         967         960
        Escambia County                121         486         444
        Etowah County                  260        1252        1155
        Fayette County                  42         186         164
        Franklin County                120         419         406
...                                    ...         ...         ...
        Lauderdale County              239         950         893
        Lawrence County                 78         344         374
        Lee County                     413        1631        1661
        Limestone County               223        1011        1002
        Lowndes County                  37         148         148
        Macon County                    65         216         210
        Madison County                 964        4249        4034
        Marengo County                  48         233         251
        Marion County                   74         291         325
        Marshall County                323        1309        1290
        Mobile County                 1346        5606        5679
        Monroe County                   56         257         246
        Montgomery County              711        3147        3117
        Morgan County                  384        1504        1395
        Perry County                    32         134         125
        Pickens County                  53         220         223
        Pike County                     93         390         412
        Randolph County                 42         221         241
        Russell County                 191         800         902
        St. Clair County               278        1101        1059
        Shelby County                  631        2478        2379
        Sumter County                   27         129         126
        Talladega County               202         854         896
        Tallapoosa County              128         467         498
        Tuscaloosa County              560        2405        2450
        Walker County                  218         814         826
        Washington County               41         169         165
        Wilcox County                   21         142         136
        Winston County                  59         252         229
Alaska  Aleutians East Borough           2          22          15

                                BIRTHS2013  BIRTHS2014  BIRTHS2015  \
STNAME  CTYNAME
Alabama Autauga County                 574         623         600
        Baldwin County                2160        2186        2240
        Barbour County                 283         260         269
        Bibb County                    259         247         253
        Blount County                  646         618         603
        Bullock County                 132         118         123
        Butler County                  240         267         257
        Calhoun County                1309        1355        1335
        Chambers County                404         421         429
        Cherokee County                232         261         250
        Chilton County                 537         586         561
        Choctaw County                 138         119         127
        Clarke County                  269         249         247
        Clay County                    121         164         149
        Cleburne County                177         186         185
        Coffee County                  617         614         616
        Colbert County                 589         587         573
        Conecuh County                 152         140         146
        Coosa County                    86          96          91
        Covington County               476         441         449
        Crenshaw County                145         131         138
        Cullman County                 952         977         960
        Dale County                    646         667         653
        Dallas County                  511         584         572
        DeKalb County                  796         839         833
        Elmore County                  986         934         948
        Escambia County                440         429         438
        Etowah County                 1145        1182        1168
        Fayette County                 186         198         186
        Franklin County                432         429         434
...                                    ...         ...         ...
        Lauderdale County              943         935         958
        Lawrence County                372         333         339
        Lee County                    1830        1860        1900
        Limestone County               976         993        1015
        Lowndes County                 140         117         118
        Macon County                   177         189         194
        Madison County                4002        4128        4185
        Marengo County                 234         260         257
        Marion County                  304         305         301
        Marshall County               1211        1226        1214
        Mobile County                 5391        5655        5585
        Monroe County                  227         201         197
        Montgomery County             3093        3168        3099
        Morgan County                 1393        1411        1406
        Perry County                   119          84          89
        Pickens County                 197         230         227
        Pike County                    350         374         368
        Randolph County                268         231         239
        Russell County                 866         897         900
        St. Clair County              1047         988        1000
        Shelby County                 2404        2333        2331
        Sumter County                  136         147         142
        Talladega County               875         869         868
        Tallapoosa County              446         470         472
        Tuscaloosa County             2399        2444        2463
        Walker County                  753         774         762
        Washington County              159         139         147
        Wilcox County                  139         131         130
        Winston County                 250         242         250
Alaska  Aleutians East Borough          15          14          14

                                POPESTIMATE2010  POPESTIMATE2011  \
STNAME  CTYNAME
Alabama Autauga County                    54660            55253
        Baldwin County                   183193           186659
        Barbour County                    27341            27226
        Bibb County                       22861            22733
        Blount County                     57373            57711
        Bullock County                    10887            10629
        Butler County                     20944            20673
        Calhoun County                   118437           117768
        Chambers County                   34098            33993
        Cherokee County                   25976            26080
        Chilton County                    43665            43739
        Choctaw County                    13841            13593
        Clarke County                     25767            25570
        Clay County                       13880            13670
        Cleburne County                   14973            14971
        Coffee County                     50177            50448
        Colbert County                    54514            54443
        Conecuh County                    13208            13121
        Coosa County                      11758            11348
        Covington County                  37796            38060
        Crenshaw County                   13853            13896
        Cullman County                    80473            80469
        Dale County                       50358            50109
        Dallas County                     43803            43178
        DeKalb County                     71142            71387
        Elmore County                     79465            80012
        Escambia County                   38309            38213
        Etowah County                    104442           104236
        Fayette County                    17231            17062
        Franklin County                   31734            31729
...                                         ...              ...
        Lauderdale County                 92747            92618
        Lawrence County                   34305            34045
        Lee County                       140782           144087
        Limestone County                  83163            85557
        Lowndes County                    11275            11119
        Macon County                      21545            21269
        Madison County                   336138           339574
        Marengo County                    20942            20708
        Marion County                     30800            30727
        Marshall County                   93146            93906
        Mobile County                    413332           413062
        Monroe County                     22982            22776
        Montgomery County                229723           231496
        Morgan County                    119603           119945
        Perry County                      10540            10510
        Pickens County                    19716            19359
        Pike County                       32957            32903
        Randolph County                   22891            22802
        Russell County                    53297            54869
        St. Clair County                  83812            84317
        Shelby County                    196048           197985
        Sumter County                     13740            13508
        Talladega County                  82071            81821
        Tallapoosa County                 41502            41453
        Tuscaloosa County                194977           196638
        Walker County                     67004            66641
        Washington County                 17610            17336
        Wilcox County                     11557            11488
        Winston County                    24401            24340
Alaska  Aleutians East Borough             3169             3254

                                POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME
Alabama Autauga County                    55175            55038
        Baldwin County                   190396           195126
        Barbour County                    27159            26973
        Bibb County                       22642            22512
        Blount County                     57776            57734
        Bullock County                    10606            10628
        Butler County                     20408            20261
        Calhoun County                   117286           116575
        Chambers County                   34075            34153
        Cherokee County                   26023            26084
        Chilton County                    43697            43795
        Choctaw County                    13543            13378
        Clarke County                     25144            25116
        Clay County                       13456            13467
        Cleburne County                   14921            15028
        Coffee County                     51173            50755
        Colbert County                    54472            54471
        Conecuh County                    12996            12875
        Coosa County                      11195            11059
        Covington County                  37818            37830
        Crenshaw County                   13951            13932
        Cullman County                    80374            80756
        Dale County                       50324            49833
        Dallas County                     42777            42021
        DeKalb County                     70942            70869
        Elmore County                     80432            80883
        Escambia County                   38034            37857
        Etowah County                    104235           103852
        Fayette County                    16960            16857
        Franklin County                   31648            31507
...                                         ...              ...
        Lauderdale County                 92680            92729
        Lawrence County                   33776            33567
        Lee County                       147899           151506
        Limestone County                  87321            88870
        Lowndes County                    10852            10725
        Macon County                      20479            19852
        Madison County                   342696           346720
        Marengo County                    20449            20210
        Marion County                     30515            30278
        Marshall County                   94228            94377
        Mobile County                    413750           414121
        Monroe County                     22585            22154
        Montgomery County                229286           227000
        Morgan County                    120112           119654
        Perry County                      10180             9993
        Pickens County                    19355            19365
        Pike County                       33105            33630
        Randolph County                   22628            22630
        Russell County                    57771            59497
        St. Clair County                  85160            86210
        Shelby County                    200830           203925
        Sumter County                     13451            13402
        Talladega County                  81931            81314
        Tallapoosa County                 41163            41191
        Tuscaloosa County                198543           200615
        Walker County                     66184            65929
        Washington County                 17115            16869
        Wilcox County                     11365            11210
        Winston County                    24176            24154
Alaska  Aleutians East Borough             3292             3314

                                POPESTIMATE2014  POPESTIMATE2015
STNAME  CTYNAME
Alabama Autauga County                    55290            55347
        Baldwin County                   199713           203709
        Barbour County                    26815            26489
        Bibb County                       22549            22583
        Blount County                     57658            57673
        Bullock County                    10829            10696
        Butler County                     20276            20154
        Calhoun County                   115993           115620
        Chambers County                   34052            34123
        Cherokee County                   25995            25859
        Chilton County                    43921            43943
        Choctaw County                    13289            13170
        Clarke County                     24847            24675
        Clay County                       13538            13555
        Cleburne County                   15072            15018
        Coffee County                     50831            51211
        Colbert County                    54480            54354
        Conecuh County                    12662            12672
        Coosa County                      10807            10724
        Covington County                  37888            37835
        Crenshaw County                   13948            13963
        Cullman County                    81221            82005
        Dale County                       49501            49565
        Dallas County                     41662            41131
        DeKalb County                     71012            71130
        Elmore County                     81022            81468
        Escambia County                   37784            37789
        Etowah County                    103452           103057
        Fayette County                    16842            16759
        Franklin County                   31592            31696
...                                         ...              ...
        Lauderdale County                 93063            92596
        Lawrence County                   33426            33115
        Lee County                       154426           156993
        Limestone County                  90612            91663
        Lowndes County                    10555            10458
        Macon County                      19387            19105
        Madison County                   350112           353089
        Marengo County                    20136            20028
        Marion County                     30246            30168
        Marshall County                   94356            94725
        Mobile County                    414926           415395
        Monroe County                     21897            21673
        Montgomery County                226389           226519
        Morgan County                    119656           119565
        Perry County                       9855             9652
        Pickens County                    20339            20864
        Pike County                       33090            33046
        Randolph County                   22486            22696
        Russell County                    59712            59660
        St. Clair County                  86561            87074
        Shelby County                    206199           208713
        Sumter County                     13243            13103

In [43]:
#to serach in data frame using multivalue index
df.loc['Alabama','Franklin County']

BIRTHS2010           120
BIRTHS2011           419
BIRTHS2012           406
BIRTHS2013           432
BIRTHS2014           429
BIRTHS2015           434
POPESTIMATE2010    31734
POPESTIMATE2011    31729
POPESTIMATE2012    31648
POPESTIMATE2013    31507
POPESTIMATE2014    31592
POPESTIMATE2015    31696
Name: (Alabama, Franklin County), dtype: int64

In [45]:
df.loc[[('Alabama','Franklin County'),('Alabama','Limestone County')]]

                          BIRTHS2010  BIRTHS2011  BIRTHS2012  BIRTHS2013  \
STNAME  CTYNAME
Alabama Franklin County          120         419         406         432
        Limestone County         223        1011        1002         976

                          BIRTHS2014  BIRTHS2015  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Franklin County          429         434            31734
        Limestone County         993        1015            83163

                          POPESTIMATE2011  POPESTIMATE2012  POPESTIMATE2013  \
STNAME  CTYNAME
Alabama Franklin County             31729            31648            31507
        Limestone County            85557            87321            88870

                          POPESTIMATE2014  POPESTIMATE2015
STNAME  CTYNAME
Alabama Franklin County             31592            31696
        Limestone County            90612            91663